Première PR, pour intégration
PaylinePaymentMethod/payment-method-equens pull request #1
Opened 2019-12-13 09:36 UTC by splanard-thales

Première pull request du moyen de paiement, pour les premiers essais d'intégration

2019-12-13 09:37 UTC, splanard-thales commented
![Capture d’écran 2019-12-13 à 10 32 49-fullpage](https://user-images.githubusercontent.com/41623216/70790032-814e9e80-1d94-11ea-9e18-f547a83f36a9.png)

2020-02-14 10:14 UTC, pesublet requested changes
Quelques retours, principalement sur du code non utilisé, à voir si on pourrait le supprimer :-)

2020-02-14 10:14 UTC, pesublet commented on build.gradle
> +    paymentMethodApiVersion = '1.5'
la 1.6 est sortie, vous devriez pouvoir l'utiliser

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/EquensErrorResponse.java
> +    public Link getLink() {
code non utilisé dans le plugin, peut être pourrait-on le supprimer si ça ne casse pas la deserialization du json ?

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/EquensApiMessage.java
> +        private String messageId = "PAYLINE" + new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date());
Mutualiser la date avec com/payline/payment/equens/bean/business/psu/PsuCreateRequest.java:30 ?

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/EquensApiMessage.java
> +                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
Mutualiser la date avec com/payline/payment/equens/bean/business/psu/PsuCreateRequest.java:51 ?

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/EquensApiMessage.java
> +    private Date messageCreateDateTime;
~Ces données membres ne semblent pas être utilisées, est-ce qu'on pourrait éventuellement les supprimer ?~
Edit: intellij les reporte en non utilisé mais elles servent pour créer le json à destination d'equens

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/fraud/PsuSessionInformation.java
> +public class PsuSessionInformation {
à part withHeaderUserAgent et withIpAddress, les autres données membres ne semblent pas utilisées

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/oauth/RFC6749AccessTokenErrorResponse.java
> +    private String errorUri;
ne semble pas utilisé

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/oauth/RFC6749AccessTokenSuccessResponse.java
> +public class RFC6749AccessTokenSuccessResponse {
scope et refreshToken ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/Account.java
> +public class Account {
currency et secondaryIdentification ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/Address.java
> +public class Address {
countrySubDivisions townName buildingNumber streetName ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/PaymentInitiationRequest.java
> +public class PaymentInitiationRequest extends EquensApiMessage {
withInitiatingPartySubId
withDebtorAccount
withUltimateDebtor
withCreditorAgent
withUltimateCreditor
withCreditorPostalAddress
withAspspPsuId
withAspspProductCode

ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/PaymentInitiationResponse.java
> +public class PaymentInitiationResponse extends EquensApiMessage {
getInitiatingPartyReferenceId
getPsuMessage
getScaChallenge
getTransactionFees
getTransactionFeeIndicator
getAuthorizationId

ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/PaymentStatusResponse.java
> +public class PaymentStatusResponse extends EquensApiMessage {
getPaymentId
getInitiatingPartyReferenceId
getScaChallenge
getFundsAvailable
getApprovalLink
getMultiAuthorizationStatus

ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/RemittanceInformationStructured.java
> +public class RemittanceInformationStructured {
withReferenceType
withReferenceIssuer

ne semblent pas utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/RiskInformation.java
> +public class RiskInformation {
withPaymentContextCode
withChannelMetaData

non utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/ScaChallenge.java
> +public class ScaChallenge {
cette classe ne semble pas utilisée

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/TransactionFees.java
> +public class TransactionFees {
cette classe ne semble pas utilisée

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/psu/Psu.java
> +public class Psu {
firstName
lastName
email
phoneNumber
status

ne semblent utilisés que dans les TU

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/psu/PsuCreateRequest.java
> +public class PsuCreateRequest extends Psu {
withMessageCreateDateTime
withMessageId

non utilisés

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/reachdirectory/GetAspspsResponse.java
> +public class GetAspspsResponse extends EquensApiMessage {
application non utilisé

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/service/LogoPaymentFormConfigurationService.java
> +        InputStream input = this.getClass().getClassLoader().getResourceAsStream( filename );
Le stream n'est pas fermé, il faudrait faire un try with resources

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/service/impl/PaymentFormConfigurationServiceImpl.java
> +    List<SelectOption> getBanks( String pluginConfiguration, String countryCode ){
Il faudrait faire un null check sur pluginConfiguration et logguer en warn si c'est null car pluginConfiguration est null tant que com.payline.payment.equens.service.impl.ConfigurationServiceImpl#retrievePluginConfiguration n'a pas été appelé

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/service/impl/PaymentWithRedirectionServiceImpl.java
> +            // TODO: check if auto-confirm is required (and functional)
todo à traiter ?

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/utils/http/PisHttpClient.java
> +        // TODO: verify the usability, and remove if necessary
TODO à vérifier

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/utils/properties/AbstractProperties.java
> +        InputStream inputStream = AbstractProperties.class.getClassLoader().getResourceAsStream(filename);
faire un try with resources pour être sûr que le stream est fermé

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/utils/security/RSAHolder.java
> +        public RSAHolderBuilder withChain( List<Certificate> chain ){
ne semble pas utilisé

2020-02-14 10:14 UTC, pesublet commented on src/main/java/com/payline/payment/equens/utils/security/RSAHolder.java
> +        public RSAHolderBuilder withPrivateKey( PrivateKey privateKey ){
ne semble pas utilisé

2020-02-14 15:21 UTC, JanFLORENT commented on src/main/java/com/payline/payment/equens/bean/business/EquensApiMessage.java
> +        private String messageId = "PAYLINE" + new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date());
En effet PsuCreateRequest et EquensApiMessage on le meme code, 
mais PsuCreateRequest hérite de Psu.
Du coup, je ne peux pas creer une classe Message qui contiendrait ce code et dont les deux classe hériteraient.

Je viens de voir que Sébastien a mis ca en commentaire de la classe PsuCreateRequest, ca confirme ce que je pensais
/**
 * The Psu create request attributes are the union of the ones from Psu class and the ones from EquensApiMessage class.
 * As Java does not allow multiple inheritance, we must copy one of the 2 sets of attributes here.
 */

2020-02-14 15:38 UTC, JanFLORENT commented on build.gradle
> +    paymentMethodApiVersion = '1.5'
on a pas la 1.6, mais on passera en 1.7 pour les fonctionnalités wallet très bientôt

2020-02-18 08:17 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/EquensApiMessage.java
> +        private String messageId = "PAYLINE" + new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date());
Exact, ça marche !

2020-02-18 08:33 UTC, pesublet commented on src/main/java/com/payline/payment/equens/bean/business/payment/Address.java
> +public class Address {
townName était bien utilisé, désolé pour l'erreur

2020-02-19 09:07 UTC, merged